/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package java.coffee.house;

/**
 *
 * @author nhoan
 */
public class Employee extends javax.swing.JFrame {

    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel16 = new javax.swing.JPanel();
        jScrollPane13 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel136 = new javax.swing.JLabel();
        txtUser10 = new javax.swing.JTextField();
        jScrollPane17 = new javax.swing.JScrollPane();
        tarAddress10 = new javax.swing.JTextArea();
        txtPass20 = new javax.swing.JPasswordField();
        jLabel137 = new javax.swing.JLabel();
        txtPass21 = new javax.swing.JPasswordField();
        jLabel138 = new javax.swing.JLabel();
        txtEmail10 = new javax.swing.JTextField();
        lb10 = new javax.swing.JLabel();
        jLabel139 = new javax.swing.JLabel();
        jLabel140 = new javax.swing.JLabel();
        jLabel141 = new javax.swing.JLabel();
        jLabel142 = new javax.swing.JLabel();
        jLabel143 = new javax.swing.JLabel();
        jLabel144 = new javax.swing.JLabel();
        btnAdd10 = new javax.swing.JButton();
        btnDelete10 = new javax.swing.JButton();
        btnEdit10 = new javax.swing.JButton();
        btnClose10 = new javax.swing.JButton();
        btnLuu = new javax.swing.JButton();
        btnReset10 = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel(){
            ImageIcon icon = new ImageIcon("image//back_glossy.png");
            public void paintComponent(Graphics g){
                Dimension d = getSize();
                g.drawImage(icon.getImage(), 0, 0, d.width, d.height, null);
                setOpaque(false);
                super.paintComponent(g);
            }
        };
        jLabel145 = new javax.swing.JLabel();
        txtNgay = new javax.swing.JTextField();
        btnLuong = new javax.swing.JButton();
        cbbLuong = new javax.swing.JComboBox();
        jLabel146 = new javax.swing.JLabel();
        jLabel147 = new javax.swing.JLabel();
        txtThuong = new javax.swing.JTextField();
        txtTienLuong = new javax.swing.JLabel();
        jLabel148 = new javax.swing.JLabel();
        Name10 = new javax.swing.JLabel();
        jLabel149 = new javax.swing.JLabel();
        jLabel154 = new javax.swing.JLabel();
        jLabel153 = new javax.swing.JLabel();
        jLabel152 = new javax.swing.JLabel();
        jLabel151 = new javax.swing.JLabel();
        jLabel150 = new javax.swing.JLabel();
        txtName10 = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));

        jPanel16.setBackground(new java.awt.Color(255, 255, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane13.setViewportView(jTable1);

        jLabel136.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel136.setForeground(new java.awt.Color(51, 51, 255));
        jLabel136.setText("EMPLOYEE MANAGEMENT");

        txtUser10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUser10ActionPerformed(evt);
            }
        });

        tarAddress10.setColumns(20);
        tarAddress10.setRows(5);
        jScrollPane17.setViewportView(tarAddress10);

        txtPass20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass20ActionPerformed(evt);
            }
        });

        jLabel137.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel137.setForeground(new java.awt.Color(255, 51, 51));
        jLabel137.setText("Confirm Password");

        txtPass21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass21ActionPerformed(evt);
            }
        });

        jLabel138.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel138.setForeground(new java.awt.Color(255, 51, 51));
        jLabel138.setText("Email :");

        txtEmail10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmail10ActionPerformed(evt);
            }
        });

        lb10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lb10.setForeground(new java.awt.Color(255, 51, 51));
        lb10.setText("Username:");

        jLabel139.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel139.setForeground(new java.awt.Color(255, 0, 0));
        jLabel139.setText("*");

        jLabel140.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel140.setForeground(new java.awt.Color(255, 51, 51));
        jLabel140.setText("Password:");

        jLabel141.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel141.setForeground(new java.awt.Color(255, 0, 0));
        jLabel141.setText("*");

        jLabel142.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel142.setForeground(new java.awt.Color(255, 0, 0));
        jLabel142.setText("*");

        jLabel143.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel143.setForeground(new java.awt.Color(255, 0, 0));
        jLabel143.setText("*");

        jLabel144.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel144.setForeground(new java.awt.Color(255, 51, 51));
        jLabel144.setText("Address:");

        btnAdd10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAdd10.setText("Add");
        btnAdd10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd10ActionPerformed(evt);
            }
        });

        btnDelete10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnDelete10.setText("Delete");
        btnDelete10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelete10ActionPerformed(evt);
            }
        });

        btnEdit10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnEdit10.setText("Change");
        btnEdit10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEdit10ActionPerformed(evt);
            }
        });

        btnClose10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnClose10.setText("Exit");
        btnClose10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose10ActionPerformed(evt);
            }
        });

        btnLuu.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLuu.setText("Save");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnReset10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnReset10.setText("Reset");
        btnReset10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReset10ActionPerformed(evt);
            }
        });

        jLabel145.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel145.setForeground(new java.awt.Color(255, 51, 51));
        jLabel145.setText("Num of working days:");

        txtNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNgayActionPerformed(evt);
            }
        });

        btnLuong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnLuong.setText("Calculate");
        btnLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuongActionPerformed(evt);
            }
        });

        cbbLuong.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        cbbLuong.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "100,000", "200,000", "300,000", "400,000" }));
        cbbLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbLuongActionPerformed(evt);
            }
        });

        jLabel146.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel146.setForeground(new java.awt.Color(255, 51, 51));
        jLabel146.setText("Salary:");

        jLabel147.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel147.setForeground(new java.awt.Color(255, 51, 51));
        jLabel147.setText("Bonus:");

        txtThuong.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtThuongCaretUpdate(evt);
            }
        });

        txtTienLuong.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        txtTienLuong.setForeground(new java.awt.Color(255, 255, 255));

        jLabel148.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel148.setForeground(new java.awt.Color(255, 51, 51));
        jLabel148.setText("Total:");

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel146)
                            .addComponent(jLabel147)
                            .addComponent(jLabel148))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addComponent(txtTienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel17Layout.createSequentialGroup()
                                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbbLuong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtThuong, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNgay, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                                .addComponent(btnLuong)
                                .addGap(21, 21, 21))))
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addComponent(jLabel145)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(txtThuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTienLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel17Layout.createSequentialGroup()
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel145)
                            .addComponent(txtNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel146)
                            .addComponent(cbbLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel147)))
                .addGap(20, 20, 20)
                .addComponent(jLabel148))
        );

        Name10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Name10.setForeground(new java.awt.Color(255, 51, 51));
        Name10.setText("Fullname:");

        jLabel149.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel149.setForeground(new java.awt.Color(255, 0, 0));
        jLabel149.setText("*");

        jLabel154.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel154.setForeground(new java.awt.Color(255, 0, 0));
        jLabel154.setText("*");

        jLabel153.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel153.setForeground(new java.awt.Color(255, 51, 51));
        jLabel153.setText("D.O.B:");

        jLabel152.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel152.setForeground(new java.awt.Color(255, 51, 51));
        jLabel152.setText("Gender:");

        jLabel151.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel151.setForeground(new java.awt.Color(255, 51, 51));
        jLabel151.setText("Phone number:");

        jLabel150.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel150.setForeground(new java.awt.Color(255, 0, 0));
        jLabel150.setText("*");

        txtName10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtName10ActionPerformed(evt);
            }
        });

        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });

        jRadioButton1.setBackground(new java.awt.Color(255, 255, 204));
        jRadioButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton1.setText("Male");

        jRadioButton2.setBackground(new java.awt.Color(255, 255, 204));
        jRadioButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jRadioButton2.setText("Female");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(377, 377, 377)
                        .addComponent(jLabel136, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnDelete10, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClose10, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAdd10, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnReset10, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit10, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtEmail10)
                            .addComponent(jScrollPane17)))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtUser10, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtPass21, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPass20))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel153)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel150))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Name10)
                            .addComponent(jLabel152))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel149)
                            .addComponent(jLabel154)))
                    .addComponent(jLabel151))
                .addGap(25, 25, 25)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtName10, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jRadioButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton2))
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(108, 108, 108))
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane13)
                .addContainerGap())
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel140)
                        .addComponent(jLabel138)
                        .addGroup(jPanel16Layout.createSequentialGroup()
                            .addComponent(jLabel144)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel143))
                        .addGroup(jPanel16Layout.createSequentialGroup()
                            .addComponent(jLabel137)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel142))
                        .addGroup(jPanel16Layout.createSequentialGroup()
                            .addComponent(lb10)
                            .addGap(8, 8, 8)
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel139)
                                .addComponent(jLabel141))))
                    .addContainerGap(921, Short.MAX_VALUE)))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel136, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(txtUser10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPass20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtPass21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtEmail10, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Name10)
                            .addComponent(jLabel154)
                            .addComponent(txtName10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel149)
                            .addComponent(jLabel152)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel153)
                            .addComponent(jLabel150))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel151)
                            .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAdd10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEdit10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReset10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClose10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnDelete10, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(52, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30))))
            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel16Layout.createSequentialGroup()
                    .addGap(232, 232, 232)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lb10)
                        .addComponent(jLabel139, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel140)
                        .addComponent(jLabel141)
                        .addGroup(jPanel16Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel142)
                                .addComponent(jLabel137))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel138)))
                    .addGap(34, 34, 34)
                    .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel144)
                        .addComponent(jLabel143))
                    .addContainerGap(279, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUser10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUser10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUser10ActionPerformed

    private void txtPass20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass20ActionPerformed

    private void txtPass21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass21ActionPerformed

    private void txtEmail10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmail10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmail10ActionPerformed

    private void btnAdd10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd10ActionPerformed
        int click = JOptionPane.showConfirmDialog(null, "Bạn có muốn thêm nhân viên mới  ?");
        while (true) {
            try {
                ps = con.prepareStatement("select * from Employee where UsernameEmp = ?");
                ps.setString(1, txtUser.getText().trim());
                rs = ps.executeQuery();
                if (txtUser.getText().trim().equals("")) {
                    JOptionPane.showMessageDialog(this, "Tài khoản không được để trống !");
                    txtUser.grabFocus();
                    return;
                } else if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Tài khoản này đã tồn tại !");
                    txtUser.grabFocus();
                    return;
                } else if (txtUser.getText().trim().length() > 30) {
                    JOptionPane.showMessageDialog(this, "Tài khoản không được lớn hơn 30 kí tự ! ");
                    txtUser.grabFocus();
                    return;
                } else if (txtUser.getText().trim().length() < 6) {
                    JOptionPane.showMessageDialog(this, "Tài khoản phải lớn hơn 6 kí tự  ! ");
                    txtUser.grabFocus();
                    return;
                } else if (!txtUser.getText().trim().matches("[A-Za-z0-9]+")) {
                    JOptionPane.showMessageDialog(this, "Tài khoản phải có chữ và số ! ");
                    txtUser.grabFocus();
                    return;
                } else {
                    break;
                }
            } catch (Exception e) {
            }

        }
        while (true) {

            if (txtPass.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống ! ");
                txtPass.grabFocus();
                return;
            } else if (txtPass.getText().trim().length() > 18) {
                JOptionPane.showMessageDialog(this, "Mật khẩu không được lớn hơn 18 kí tự ! ");
                txtPass.grabFocus();
                return;
            } else if (txtPass.getText().trim().length() < 6) {
                JOptionPane.showMessageDialog(this, "Mật khẩu phải lớn hơn 6 kí tự  ! ");
                txtPass.grabFocus();
                return;
            } else if (!txtPass.getText().matches("[A-Za-z0-9]+")) {
                JOptionPane.showMessageDialog(this, "Mật khẩu không được có khoảng cách và kí tự đặc biệt ! ");
                txtPass.grabFocus();
                return;
            } else {
                break;
            }

        }
        while (true) {
            if (txtPass1.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu không được để trống !");
                txtPass1.grabFocus();
                return;
            } else if (!txtPass1.getText().trim().equals(txtPass.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu phải giống mật khẩu !");
                txtPass1.grabFocus();
                return;
            } else {
                break;
            }

        }
        while (true) {
            if (txtName.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Họ và tên không được để trống !");
                txtName.grabFocus();
                return;
            } else if (txtName.getText().trim().length() > 30) {
                JOptionPane.showMessageDialog(this, "Tên không được lớn hơn 30 kí tự ! ");
                txtName.grabFocus();
                return;
            }
            {
                break;
            }

        }
        while (true) {
            if (ftError.format(txtBirthday.getDate()).compareTo("2000/01/01") >= 0) {
                JOptionPane.showMessageDialog(this, "Nhân viên phải đủ 18 tuổi !");
                txtBirthday.grabFocus();
                return;
            } else {
                break;
            }

        }
        if (!txtPhone.getText().trim().equals("")) {
            while (true) {
                if (txtPhone.getText().trim().length() > 11 || txtPhone.getText().trim().length() < 10) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại gồm 10-11 số.");
                    txtPhone.grabFocus();
                    return;
                } else if (!txtPhone.getText().trim().matches("0[1-9]{1}\\d{8,9}")) {
                    JOptionPane.showMessageDialog(this, "Không đúng định dạng số điện thoại ! Ví dụ : 012345678x hoặc 098765432x");
                    txtPhone.grabFocus();
                    return;
                } else {
                    break;
                }

            }
        }
        if (!txtEmail.getText().trim().equals("")) {
            while (true) {
                if (!txtEmail.getText().trim().matches("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$")) {
                JOptionPane.showMessageDialog(this, "Không đúng định dạng Email ! Ví dụ : (abcdef@gmail.com) ");
                txtEmail.grabFocus();
                return;
            } else {
                break;
            }
        }
        }
        while (true) {
            if (tarAddress.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống !");
                tarAddress.grabFocus();
                return;
            } else if (tarAddress.getText().trim().length() > 100) {
                JOptionPane.showMessageDialog(this, "Địa chỉ không được lớn hơn 100 kí tự ! ");
                tarAddress.grabFocus();
                return;
            } else {
                break;
            }

        }
        while (true) {
            if (txtHinh.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Hình ảnh không được để trống !");
                txtHinh.grabFocus();
                return;
            } else {
                break;
            }

        }

        try {
            ps = con.prepareStatement("Insert into Employee values(?,?,?,?,?,?,?,?,?)");
            ps.setString(1, txtUser.getText());
            ps.setString(2, txtPass.getText());
            ps.setString(3, txtName.getText());
            if (rdMale.isSelected()) {
                ps.setString(4, "Nam");
            } else {
                ps.setString(4, "Nữ");
            }
            ps.setString(5, ft.format(txtBirthday.getDate()));
            ps.setString(6, txtPhone.getText());
            ps.setString(7, txtEmail.getText());
            ps.setString(8, tarAddress.getText());
            ps.setString(9, txtHinh.getText());

            ps.executeUpdate();
            tblModel.getDataVector().removeAllElements();
            loadData();

            JOptionPane.showMessageDialog(this, "Thêm tài khoản thành công ! ");
        } catch (SQLException ex) {
            Logger.getLogger(EmployeeManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAdd10ActionPerformed

    private void btnDelete10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelete10ActionPerformed
        int click = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn xóa ?");
        if (click == 0) {
            try {
                ps = con.prepareStatement("select * from [Order] where UsernameEmp=?");
                ps.setString(1, txtUser.getText());
                rs = ps.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(null, "Nhân viên đang còn đơn hàng, không thể xóa.");
                } else {
                    try {
                        ps = con.prepareStatement("Delete from Employee where UsernameEmp=?");
                        ps.setString(1, txtUser.getText());
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Xóa thành công ! ");
                        btnResetActionPerformed(evt);
                        tblModel.getDataVector().removeAllElements();
                        loadData();
                    } catch (Exception e) {
                    }
                }
            } catch (SQLException ex) {
                Logger.getLogger(EmployeeManager.class.getName()).log(Level.SEVERE, null, ex);
            }

        }        // TODO add your handling code here:
    }//GEN-LAST:event_btnDelete10ActionPerformed

    private void btnEdit10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEdit10ActionPerformed
        txtUser.setEnabled(false);
        btnDelete.setEnabled(true);
        btnEdit.setEnabled(true);
        btnAdd.setEnabled(false);
        btnLuu.setEnabled(true);
        btnBrowse.setEnabled(true);
        txtPass.setEnabled(true);
        txtPass1.setEnabled(true);
        txtEmail.setEnabled(true);
        tarAddress.setEnabled(true);
        txtName.setEnabled(true);
        txtPhone.setEnabled(true);
        txtBirthday.setEnabled(true);
        txtHinh.setEnabled(true);
        rdFemale.setEnabled(true);
        rdMale.setEnabled(true);
        btnEdit.setEnabled(false);
    }//GEN-LAST:event_btnEdit10ActionPerformed

    private void btnClose10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose10ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnClose10ActionPerformed

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        int click = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn lưu ?");
        while (true) {
            if (txtPass.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Mật khẩu không được để trống ! ");
                txtPass.grabFocus();
                return;
            } else if (txtPass.getText().trim().length() > 18) {
                JOptionPane.showMessageDialog(this, "Mật khẩu không được lớn hơn 18 kí tự ! ");
                txtPass.grabFocus();
                return;
            } else if (txtPass.getText().trim().length() < 6) {
                JOptionPane.showMessageDialog(this, "Mật khẩu phải lớn hơn 6 kí tự  ! ");
                txtPass.grabFocus();
                return;
            } else {
                break;
            }

        }
        while (true) {
            if (txtPass1.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu không được để trống !");
                txtPass1.grabFocus();
                return;
            } else if (!txtPass1.getText().trim().equals(txtPass.getText().trim())) {
                JOptionPane.showMessageDialog(this, "Xác nhận mật khẩu phải giống mật khẩu !");
                txtPass1.grabFocus();
                return;
            } else {
                break;
            }

        }
        while (true) {
            if (txtName.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Họ và tên không được để trống !");
                txtName.grabFocus();
                return;
            } else if (txtName.getText().trim().length() > 30) {
                JOptionPane.showMessageDialog(this, "Họ và tên không được lớn hơn 30 kí tự ! ");
                txtName.grabFocus();
                return;
            }
            {
                break;
            }

        }
        while (true) {
            if (ftError.format(txtBirthday.getDate()).compareTo("2000/01/01") >= 0) {
                JOptionPane.showMessageDialog(this, "Nhân viên phải đủ 18 tuổi ! ");
                txtBirthday.grabFocus();
                return;
            } else {
                break;
            }

        }
        if (!txtPhone.getText().trim().equals("")) {
            while (true) {
                if (txtPhone.getText().trim().length() > 11 || txtPhone.getText().trim().length() < 10) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại gồm 10-11 số.");
                    txtPhone.grabFocus();
                    return;
                } else if (!txtPhone.getText().trim().matches("0[1-9]{1}\\d{8,9}")) {
                    JOptionPane.showMessageDialog(this, "Không đúng định dạng số điện thoại ! Ví dụ : 012345678x hoặc 098765432x");
                    txtPhone.grabFocus();
                    return;
                } else {
                    break;
                }

            }
        }
        if (!txtEmail.getText().trim().equals("")) {
            while (true) {
                if (!txtEmail.getText().trim().matches("^[_A-Za-z0-9-\\+]+(\\.[_A-Za-z0-9-]+)*@"
                    + "[A-Za-z0-9-]+(\\.[A-Za-z0-9]+)*(\\.[A-Za-z]{2,})$")) {
                JOptionPane.showMessageDialog(this, "Không đúng định dạng Email ! Ví dụ : (abcdef@gmail.com) ");
                txtEmail.grabFocus();
                return;
            } else {
                break;
            }
        }
        }
        while (true) {
            if (tarAddress.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Địa chỉ không được để trống !");
                tarAddress.grabFocus();
                return;
            } else if (tarAddress.getText().trim().length() > 100) {
                JOptionPane.showMessageDialog(this, "Địa chỉ không được lớn hơn 100 kí tự ! ");
                tarAddress.grabFocus();
                return;
            }
            {
                break;
            }

        }
        while (true) {
            if (txtHinh.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(this, "Hình ảnh không được để trống !");
                txtHinh.grabFocus();
                return;
            } else {
                break;
            }
        }

        try {
            ps = con.prepareStatement("update Employee set Password=?,NameEmp=?,Gender=?,Birthday=?,Phone=?,Email=?,Address=?,Hinh=? where UsernameEmp=?");

            ps.setString(9, txtUser.getText());
            ps.setString(1, txtPass.getText());
            ps.setString(2, txtName.getText());
            ps.setString(4, ft.format(txtBirthday.getDate()));
            ps.setString(5, txtPhone.getText());
            ps.setString(6, txtEmail.getText());
            ps.setString(7, tarAddress.getText());
            ps.setString(8, txtHinh.getText());
            if (rdMale.isSelected()) {
                ps.setString(3, "Nam");
            } else {
                ps.setString(3, "Nữ");
            }

            ps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Lưu thành công ! ");
            tblModel.getDataVector().removeAllElements();
            loadData();
            btnResetActionPerformed(evt);
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnReset10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReset10ActionPerformed
        txtUser.setText("");
        txtName.setText("");
        txtEmail.setText("");
        txtPass.setText("");
        txtPass1.setText("");
        txtPhone.setText("");
        tarAddress.setText("");
        img.setImageLabel(lbHinh, "image//trongsuot.png");
        txtHinh.setText("");
        rdMale.setSelected(true);
        btnDelete.setEnabled(false);
        btnEdit.setEnabled(false);
        btnAdd.setEnabled(true);
        btnLuu.setEnabled(false);
        txtUser.setEnabled(true);
        tblModel.getDataVector().removeAllElements();
        txtTienLuong.setText("");
        txtThuong.setText("");
        txtNgay.setText("");
        cbbLuong.setSelectedIndex(0);
        txtPass.setEnabled(true);
        txtPass1.setEnabled(true);
        txtEmail.setEnabled(true);
        tarAddress.setEnabled(true);
        txtName.setEnabled(true);
        txtPhone.setEnabled(true);
        txtBirthday.setEnabled(true);
        txtHinh.setEnabled(true);
        rdFemale.setEnabled(true);
        rdMale.setEnabled(true);
        btnBrowse.setEnabled(true);

        loadData();
    }//GEN-LAST:event_btnReset10ActionPerformed

    private void txtNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNgayActionPerformed

    private void btnLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuongActionPerformed
        while (true) {
            if (txtNgay.getText().trim().equals("")) {
                JOptionPane.showMessageDialog(null, "Số ngày làm việc không được bỏ trống ! ");
                return;
            } else if (!txtNgay.getText().trim().matches("[0-9]+")) {
                JOptionPane.showMessageDialog(null, "Ngày làm việc phải là số ! ");
                return;
            } else if (Double.parseDouble(txtNgay.getText().trim()) > 31) {
                JOptionPane.showMessageDialog(null, "Số ngày làm việc phải nhỏ hơn 31");
                return;
            } else {
                break;
            }
        }
        double ngay = Double.parseDouble(txtNgay.getText().trim());
        String a = (String) cbbLuong.getSelectedItem();
        double LuongCB = Double.parseDouble(a.replaceAll(",", ""));
        double TienLuong;

        if (txtThuong.getText().trim().equals("")) {
            TienLuong = ngay * LuongCB;
        } else {
            while (true) {
                if (!txtThuong.getText().trim().matches("[0-9]+")) {
                    JOptionPane.showMessageDialog(null, "Tiền thưởng phải là số ! ");
                    return;
                } else if (Double.parseDouble(txtThuong.getText().trim()) > 500000) {
                    JOptionPane.showMessageDialog(null, "Tiền thưởng phải nhỏ hơn 500.000 ");
                    return;
                } else {
                    break;
                }
            }
            double Thuong = Double.parseDouble(txtThuong.getText().trim());
            TienLuong = (ngay * LuongCB) + Thuong;
        }
        txtTienLuong.setText(String.valueOf(nft.format(TienLuong)) + " VNĐ");
    }//GEN-LAST:event_btnLuongActionPerformed

    private void cbbLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbLuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbLuongActionPerformed

    private void txtThuongCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtThuongCaretUpdate

    }//GEN-LAST:event_txtThuongCaretUpdate

    private void txtName10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtName10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtName10ActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Name10;
    private javax.swing.JButton btnAdd10;
    private javax.swing.JButton btnClose10;
    private javax.swing.JButton btnDelete10;
    private javax.swing.JButton btnEdit10;
    private javax.swing.JButton btnLuong;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnReset10;
    private javax.swing.JComboBox cbbLuong;
    private javax.swing.JLabel jLabel136;
    private javax.swing.JLabel jLabel137;
    private javax.swing.JLabel jLabel138;
    private javax.swing.JLabel jLabel139;
    private javax.swing.JLabel jLabel140;
    private javax.swing.JLabel jLabel141;
    private javax.swing.JLabel jLabel142;
    private javax.swing.JLabel jLabel143;
    private javax.swing.JLabel jLabel144;
    private javax.swing.JLabel jLabel145;
    private javax.swing.JLabel jLabel146;
    private javax.swing.JLabel jLabel147;
    private javax.swing.JLabel jLabel148;
    private javax.swing.JLabel jLabel149;
    private javax.swing.JLabel jLabel150;
    private javax.swing.JLabel jLabel151;
    private javax.swing.JLabel jLabel152;
    private javax.swing.JLabel jLabel153;
    private javax.swing.JLabel jLabel154;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lb10;
    private javax.swing.JTextArea tarAddress10;
    private javax.swing.JTextField txtEmail10;
    private javax.swing.JTextField txtName10;
    private javax.swing.JTextField txtNgay;
    private javax.swing.JPasswordField txtPass20;
    private javax.swing.JPasswordField txtPass21;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtThuong;
    private javax.swing.JLabel txtTienLuong;
    private javax.swing.JTextField txtUser10;
    // End of variables declaration//GEN-END:variables
}
